name: CI

on:
  pull_request:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: lib-tiny-fp
  DOCKER_CONTAINER_NAME: lib-tiny-fp-builder

jobs:

  build:

    name: Build and test
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Testing
      run: |
        docker build -t ${{ env.DOCKER_IMAGE_NAME }} . --file ./build/Dockerfile.test

    - name: Cleanup
      run: |
        docker rmi ${{ env.DOCKER_IMAGE_NAME }}
