name: CI

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: lib-tiny-fp
  DOCKER_CONTAINER_NAME: lib-tiny-fp-builder

jobs:

  build:

    name: Create artifact release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Cleanup
      run: |
        rm -rf /opt/hostedtoolcache

    - name: Build artifact
      run: |
        docker build -t ${{ env.DOCKER_IMAGE_NAME }} . --file ./build/Dockerfile.builder
        docker run -d --name ${{ env.DOCKER_CONTAINER_NAME }} ${{ env.DOCKER_IMAGE_NAME }}

    - name: Execute test
      run: |
        docker exec -t ${{ env.DOCKER_CONTAINER_NAME }} /test/test
        docker stop ${{ env.DOCKER_CONTAINER_NAME }}

    - name: Create release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        VERSION=$(cat version)
        gh release create $VERSION -t "$VERSION" -n "$VERSION"

    - name: Cleanup
      run: |
        docker rm ${{ env.DOCKER_CONTAINER_NAME }}
        docker rmi ${{ env.DOCKER_IMAGE_NAME }}
