name: Publish

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: lib-tiny-fp-release
  DOCKER_CONTAINER_NAME: lib-tiny-fp-builder

jobs:

  build:

    name: Create artifact release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Build artifact
      run: |
        docker build -t ${{ env.DOCKER_IMAGE_NAME }} . --file ./build/Dockerfile.rel
        docker run -d --name ${{ env.DOCKER_CONTAINER_NAME }} ${{ env.DOCKER_IMAGE_NAME }}

    - name: Get artifact
      run: |
        #
        # create folder containing the artifact
        mkdir -p package

        #
        # Copy the artifact from the container to the host
        docker cp ${{ env.DOCKER_CONTAINER_NAME }}:tinyfp/_release/libtinyfp.so ./package

        #
        # create a tarball containing the includes
        docker exec ${{ env.DOCKER_CONTAINER_NAME }} bash -c 'cd /tinyfp/src && find . -name "*.h*" -print0 | tar -cvf /tinyfp/includes.tar -T -'

        #
        # Copy the includes from the container to the host
        docker cp ${{ env.DOCKER_CONTAINER_NAME }}:/tinyfp/includes.tar ./package
        docker stop ${{ env.DOCKER_CONTAINER_NAME }}

        #
        # Copying installation fles
        cp ./setup/tinyfp.pc ./package
        cp ./setup/setup.sh ./package

        #
        # Extract the includes
        cd package && tar -xvf includes.tar && rm includes.tar

    - name: Create release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        VERSION=$(cat version)
        tar -czvf tiny-fp-$VERSION.tgz ./package
        gh release create $VERSION -t "tinyfp $VERSION" -n "tinyfp version: $VERSION" ./tiny-fp-$VERSION.tgz

    - name: Cleanup
      run: |
        docker rm ${{ env.DOCKER_CONTAINER_NAME }}
        docker rmi ${{ env.DOCKER_IMAGE_NAME }}
